---
title: "phyloseq try"
output: html_document
date: "2022-11-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
rm(list = ls())
```

```{r}
library(phyloseq)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(DT)
library(stringr)
```

```{r}
data("enterotype")
enterotype
```

```{r}
tax_table(enterotype) %>% head()
```

```{r}
data("esophagus")
esophagus
```

```{r}
data("soilrep")
soilrep
```
```{r}
data("GlobalPatterns")
GlobalPatterns
```


```{r}
GP_sp <- subset_taxa(GlobalPatterns, Species!="NA")
GP_sp
```


```{r}
GP_sp_tutorial = subset_samples(GP_sp, SampleType %in% c("Freshwater", "Freshwater (creek)", "Skin", "Tongue"))
GP_sp_tutorial
```
```{r}
GP_sp_tutorial_sample_data = sample_data(GP_sp_tutorial)
GP_sp_tutorial_sample_data
```
```{r}

GP_sp_tutorial_sample_data_df = GP_sp_tutorial_sample_data %>%
  #rownames_to_column("sampleid")  %>% # this gives some error
  as_data_frame() %>%
 mutate(sampleid = X.SampleID) %>%
 mutate(SampleOrigin = SampleType) %>%
 mutate(SampleOrigin = str_replace(SampleOrigin, "Skin", "Human")) %>%
  mutate(SampleOrigin = str_replace(SampleOrigin, "Tongue", "Human")) %>%
  mutate(SampleOrigin = str_replace(SampleOrigin, "Freshwater \\(creek\\)", "Freshwater")) %>% 
  relocate(sampleid, SampleOrigin)
  
GP_sp_tutorial_sample_data_df
```

```{r}
write.table(GP_sp_tutorial_sample_data_df, "./tutorial_files/GP_sp_tutorial_sample_data_df.csv",
            row.names = F,
            sep = "\t",
            quote = F)
```


```{r}
GP_sp_tutorial_otu_table_df = otu_table(GP_sp_tutorial) %>% 
  as.data.frame() %>% 
  rownames_to_column("otus")
GP_sp_tutorial_otu_table_df

write.table(GP_sp_tutorial_otu_table_df, "./tutorial_files/GP_sp_tutorial_otu_table_df.csv",
            row.names = F,
            sep = "\t",
            quote = F)
```


```{r}
GP_sp_tutorial_tax_table_df = tax_table(GP_sp_tutorial) %>% 
  as.data.frame() %>% 
  rownames_to_column("otus")
GP_sp_tutorial_tax_table_df

write.table(GP_sp_tutorial_tax_table_df, "./tutorial_files/GP_sp_tutorial_tax_table_df.csv",
            row.names = F,
            sep = "\t",
            quote = F)
```
```{r}
GP_sp_tutorial_phy_tree = phy_tree(GP_sp_tutorial)
GP_sp_tutorial_phy_tree

ape::write.tree(GP_sp_tutorial_phy_tree, "./tutorial_files/GP_sp_tutorial_phy_tree.tree")

```




